# -*- coding: utf-8 -*-
"""SevCatOneNumNestedOneObsPerGroup

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ga3BF1tKN4HGUuI4hm8s5ugFNqVrXmGx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/11_SevCatOneNumNestedOneObsPerGroup.csv")
df.describe()

# check out missing Values
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_df = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_df.head(20)

# Select only numeric data and impute missing values as 0
numerics = ['uint8','int16', 'int32', 'int64', 'float16', 'float32', 'float64']
data = df \
.select_dtypes(include=numerics) \
.fillna(0) \
.values

pip install squarify

# Treemap
import squarify 
a = df.groupby('Continent')[['value']].sum().index.get_level_values(0).tolist()
d = df.groupby('Continent')[['value']].sum().reset_index().value.values.tolist()
squarify.plot(sizes=d,label=a, alpha=.8 )
plt.axis('off')
plt.show()

# Circle packing
import circlify
g = circlify.circlify(df['value'].tolist(), show_enclosure=False, target_enclosure=circlify.Circle(x=0, y=0, r=1))
fig, ax = plt.subplots(figsize=(10,10))
limit = max(
    max(abs(g.x) + g.r,abs(g.y) + g.r,)
    for i in g
)
plt.xlim(-limit, limit)
plt.ylim(-limit, limit)
labels = df['Continent','Region','Country']

for i, label in zip(g, labels):
    x, y, r = i
    ax.add_patch(plt.Circle((x, y), r, alpha=0.2, linewidth=2))
    plt.annotate(label, (x,y ) ,va='center',ha='center')

# Lollipop
fig, (ax1) = plt.subplots(1)
ordered_df = df.sort_values(by='value',ascending=True).reset_index(drop=True)
sns.scatterplot(x=df["value"],y=df['Continent','Region','Country'],s=150,alpha=1,label="Average",color="skyblue",edgecolors="white",)
sns.scatterplot(x=df["value"],y=df['Continent','Region','Country'],s=150,alpha=1,label="Min/Max",color="blue",edgecolors="white",)
sns.scatterplot(x=df["value"],y=df['Continent','Region','Country'],s=150,alpha=1,color="skyblue",edgecolors="white",)
ax1.hlines(y=df['Continent','Region','Country'],xmin=df["value"],xmax=df["value"],color="grey",alpha=0.4,lw=4,zorder=0, )
plt.show()

# Circular barplot
df = df.sort_values(by=['value'])
plt.figure(figsize=(200,100))
ax = plt.subplot(111, polar=True)
plt.axis('off')

upperLimit = 1000
lowerLimit = 30
labelPadding = 4
max = df['value'].max()

slope = (max - lowerLimit) / max
heights = slope * df.value + lowerLimit
width = 2*np.pi / len(df.index)
indexes = list(range(1, len(df.index)+1))
angles = [element * width for element in indexes]
angles
bars = ax.bar(
x=angles,height=heights, width=width,bottom=lowerLimit,linewidth=2, edgecolor="white",color="#61a4b2",)

for bar,angle,height,label in zip(bars,angles, heights, df['Continent','Region','Country']):
    rotation = np.rad2deg(angle)
    alignment = ""
    if angle >= np.pi/2 and angle < 3*np.pi/2:
        alignment = "right"
        rotation = rotation + 180
    else: 
        alignment = "left"
    ax.text(x=angle, y=lowerLimit + bar.get_height() + labelPadding, s=label, ha=alignment, va='center', rotation=rotation, rotation_mode="anchor") 
    plt.show()