# -*- coding: utf-8 -*-
"""story_3Life expectancy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b6N3pE6YgCRD7YPIO_jmPAk71-BpfLx_
"""

import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objs as go
from plotly.subplots import make_subplots
import numpy as np

import seaborn as sns

# Load the dataset
data = px.data.gapminder().query("year == 2007")

# Round the gdpPercap values
data['gdpPercap'] = round(data['gdpPercap'], 0)

# Format the population values to millions
data['pop'] = round(data['pop'] / 1000000, 2)

# Round the lifeExp values
data['lifeExp'] = round(data['lifeExp'], 1)

# Create the scatter plot with labels
fig = px.scatter(data, x='gdpPercap', y='lifeExp', size='pop', color='continent', hover_name='country', log_x=True, size_max=60)
fig.update_layout(title='GDP per capita vs. Life expectancy in 2007', xaxis_title='GDP per capita (USD)', yaxis_title='Life expectancy (years)', legend_title='Continent')

# Show the plot
fig.show()

# Create the two subplots
fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(12, 6))

# Plot 1: GDP per capita vs population
sns.scatterplot(data=data, x='gdpPercap', y='pop', hue='continent',
                size='lifeExp', sizes=(50, 1000), alpha=0.7, ax=ax1)
ax1.set_xscale('log')
ax1.set_yscale('log')
ax1.set_xlabel('GDP per capita (log scale)')
ax1.set_ylabel('Population (log scale)')
ax1.set_title('GDP per capita vs population by continent')

# Plot 2: Life expectancy vs population
sns.scatterplot(data=data, x='lifeExp', y='pop', hue='continent',
                size='gdpPercap', sizes=(50, 1000), alpha=0.7, ax=ax2)
ax2.set_xscale('log')
ax2.set_yscale('log')
ax2.set_xlabel('Life expectancy (log scale)')
ax2.set_ylabel('Population (log scale)')
ax2.set_title('Life expectancy vs population by continent')

# Show the plot
plt.show()

